Navbar + funcionalidad responsive
alkemyTech/Hasar-React-W1 pull request #2
Opened 2023-02-26 20:50 UTC by MarceCarabajal

Creación de componente para el navbar principal

El mismo incluye:
Logo Alkamy.
Usuario.
Listado de links a las diferentes secciones.
Se agrego la funcionalidad responsive para distintos dispositivos.
![image](https://user-images.githubusercontent.com/126085506/221436370-863e07cc-d474-4b0a-8513-de09819c6c94.png)
![image](https://user-images.githubusercontent.com/126085506/221436463-db60392b-c9b9-4366-a51d-2d5b5686b7ea.png)

2023-02-27 23:20 UTC, rodrigotonso requested changes

2023-02-27 23:20 UTC, rodrigotonso commented on src/components/header/NavBar.js
> +import { AppBar, Button, Drawer, IconButton, Toolbar, Typography } from "@mui/material";
este archivo es un componente llamado NavBar dentro de una carpeta llamada header

Es probable que termine mareando, lo tradicional es poner los componentes dentro de carpetas con el mismo nombre.

Tambien para saber que es un componente lo que hay dentro del archivo se suele usar la extensión jsx (hoy en día no hay diferencia en código es solo para identificar en un vistazo)

2023-02-27 23:20 UTC, rodrigotonso commented on src/components/header/NavBar.js
> +        title: "Usuario", path: "#user", icon: <PersonIcon />
estan raros los estilos, pdríamos ponernos de acuerdo y usar las reglas prettier de última

2023-02-27 23:20 UTC, rodrigotonso commented on src/components/header/NavBar.js
> +
Este enter me suena de más

2023-02-27 23:20 UTC, rodrigotonso commented on src/components/header/NavListDrawer.js
> +                        <ListItemIcon>
falta indentado

2023-02-27 23:20 UTC, rodrigotonso commented on src/components/header/NavListDrawer.js
> +                        component="a"
el atributo no es required, podríamos volarlo hasta que lo necesitemos

2023-02-27 23:20 UTC, rodrigotonso commented on src/components/header/NavBar.js
> +                        Alkibank
tendría más sentido un link siempre se suele hacer que redireccion a la home

2023-02-27 23:20 UTC, rodrigotonso commented on src/components/header/NavBar.js
> +                            <Button color="inherit" key={item.title} component="a" href={item.path}>{item.title}</Button>
onClick tal vez va mejor que el path, es probable que en la navbar queramos hacer más cosas, de momento cerrarla cuando elegimos una opción

2023-02-28 15:31 UTC, MarceCarabajal commented on src/components/header/NavBar.js
> +import { AppBar, Button, Drawer, IconButton, Toolbar, Typography } from "@mui/material";
Es cierto, ya modifiqué el nombre de la carpeta por "navbar" y a los archivos les puse extension .jsx

2023-02-28 15:32 UTC, MarceCarabajal commented on src/components/header/NavBar.js
> +        title: "Usuario", path: "#user", icon: <PersonIcon />
Sí, me fui dando un poco de cuenta durante la marcha, pero ya formatee todo a Prettier

2023-02-28 15:32 UTC, MarceCarabajal commented on src/components/header/NavBar.js
> +
Solucionado

2023-02-28 15:32 UTC, MarceCarabajal commented on src/components/header/NavListDrawer.js
> +                        <ListItemIcon>
Tal cual, ya se modificó

2023-02-28 15:33 UTC, MarceCarabajal commented on src/components/header/NavListDrawer.js
> +                        component="a"
Perfecto, en la nueva version se modificó

2023-02-28 15:35 UTC, MarceCarabajal commented on src/components/header/NavBar.js
> +                        Alkibank
Tal cual, funcionalidad agregada al icono de inicio con react-router-dom, con NavLink

2023-02-28 15:42 UTC, MarceCarabajal commented on src/components/header/NavBar.js
> +                            <Button color="inherit" key={item.title} component="a" href={item.path}>{item.title}</Button>
Lo que hice fue primero cambiar de nombre de mi lista de secciones a mi NavLink (array de objetos) por NavArrayLink y dejarlo en App para luego mandarlo por props a NavBar y NavListDrawer. El onClick lo puse dentro de IconButton con un estado para que pueda abrir y cerrar el menu

2023-03-02 02:37 UTC, rodrigotonso requested changes

2023-03-02 02:37 UTC, rodrigotonso commented on src/App.jsx
> +export default App;
Quedo el archivo app (archivo raiz del proyecto muy cargado
Podríamos envíar el array navArrayLinks dentro de una folder llamada constants por ejemplo
las rutas a un archivo llamado routes.jsx dentro de una carpeta llamada router o routes o config
y luego importalos aca

2023-03-02 02:37 UTC, rodrigotonso commented on src/index.jsx
> +);
aca tambien podríamos sacar el theme afuera para intentar que quede más limpio el index

2023-03-02 02:37 UTC, rodrigotonso commented on src/pages/CargaSaldo.jsx
> +          //   transform:"scale(1.05)",
evitemos el código comentado

2023-03-02 12:55 UTC, MarceCarabajal commented on src/App.jsx
> +export default App;
Es verdad, ya se encuentra realizada esta solicitud en la nueva version

2023-03-02 13:07 UTC, MarceCarabajal commented on src/index.jsx
> +);
Se encuentra realizada esta solicitud en la nueva version

2023-03-02 13:07 UTC, MarceCarabajal commented on src/pages/CargaSaldo.jsx
> +          //   transform:"scale(1.05)",
Se encuentra realizada esta solicitud en la nueva version

2023-03-03 18:58 UTC, rodrigotonso approved these changes

2023-03-05 18:18 UTC, merged