W1 20
alkemyTech/Hasar-React-W1 pull request #5
Opened 2023-03-01 16:45 UTC by diegodiazdev7

Creacion de componente title

2023-03-02 02:22 UTC, rodrigotonso commented
Intentemos agregar el link al ticket en los PR

2023-03-02 02:24 UTC, rodrigotonso requested changes

2023-03-02 02:24 UTC, rodrigotonso commented on src/components/Title.jsx
> +import React from 'react'
Agregar dentro de una carpeta title

2023-03-02 02:24 UTC, rodrigotonso commented on src/components/Title.jsx
> +
muchos espacios innecesarios????

2023-03-02 02:24 UTC, rodrigotonso commented on src/components/Title.jsx
> +        <Box sx={{ fontSize: `${size}.fontSize`, m: 1 }}>
si envío como size='cualquiercosa' o no envío size que pasaría???

2023-03-02 16:03 UTC, diegodiazdev7 commented on src/components/Title.jsx
> +        <Box sx={{ fontSize: `${size}.fontSize`, m: 1 }}>
Ya hice esas validaciones Rodri :D

2023-03-03 18:58 UTC, rodrigotonso approved these changes

2023-03-05 18:10 UTC, merged